In [1]:
import numpy as np

In [3]:
liste = range(1,9)
a = np.array(liste)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.array(range(1,6))

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(8,)

In [7]:
a[-1]

8

In [9]:
b = np.array([[1, 2, 3], [6, 7, 8]])

In [10]:
b.shape

(2, 3)

In [11]:
b[1, 1] = 0

In [12]:
b

array([[1, 2, 3],
       [6, 0, 8]])

In [14]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
c.shape

(3, 3)

In [16]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
c[1, 1]

5

In [19]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((2, 2), -1)

array([[-1, -1],
       [-1, -1]])

In [50]:
np.empty((3, 1))

array([[ 6.19314158e-312],
       [ 0.00000000e+000],
       [-6.47591605e-319]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.arange(5, 50, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [30]:
np.linspace(2, 30 , 5)

array([ 2.,  9., 16., 23., 30.])

In [62]:
np.empty((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.random.random((3, 3))

array([[0.20455242, 0.45238479, 0.85486112],
       [0.61756868, 0.89287872, 0.88041788],
       [0.84743924, 0.67868226, 0.99439748]])

In [63]:
z = np.random.randint(2, 15, size = (3, 5))

In [64]:
z.shape

(3, 5)

In [67]:
z.reshape((5, 3))

array([[ 6,  4, 11],
       [10,  7,  8],
       [ 5, 11,  5],
       [ 7,  5, 13],
       [ 6,  8,  3]])

In [68]:
z.max()

13

In [69]:
z.min()

3

In [70]:
z.argmax()

11

In [72]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[-1, 3], [7, 9]])

In [73]:
np.hstack((a, b))

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [74]:
np.vstack((a, b))

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [75]:
dizi = np.array (range(10)).reshape(5, 2)

In [76]:
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [79]:
dizi_1 = np.array (range(3,13)).reshape(5, 2)

In [80]:
np.concatenate([dizi, dizi_1], axis = 1)

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [81]:
np.concatenate([dizi, dizi_1], axis = 0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
array1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [84]:
array1.shape

(3, 4)

In [86]:
array1[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [87]:
array2 = array1.copy()

In [89]:
array2[1, 1] = -6
array2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
m = np.array(range(1, 13)).reshape(4, 3)

In [93]:
m[m>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [95]:
a

array([[1, 2],
       [3, 4]])

In [96]:
b

array([[-1,  3],
       [ 7,  9]])

In [94]:
np.subtract(a, b)

array([[ 2, -1],
       [-4, -5]])

In [98]:
a* b

array([[-1,  6],
       [21, 36]])

In [100]:
np.dot(a, b)

array([[13, 21],
       [25, 45]])

In [105]:
a @ b  # matrix çarpım - np.dot() ile aynı

array([[13, 21],
       [25, 45]])

In [107]:
a ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [110]:
x = np.square(a)
x


array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [111]:
y = np.sqrt(a)
y

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [112]:
np.exp(3)

20.085536923187668

In [114]:
np.log(100)

4.605170185988092

In [116]:
np.log10(100)

2.0

In [115]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])